imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyAppUserBundle/Resources/config/services.yml" }
    - { resource: "@NadaAutoEcoleBundle/Resources/config/services.yml" }
    - { resource: "@DataBundle/Resources/config/services.yml" }
    - { resource: "@NadaMapBundle/Resources/config/services.yml" }
    - { resource: "@GrapheBundle/Resources/config/services.yml" }
    - { resource: "@FarahChatBundle/Resources/config/services.yml" }
    - { resource: "@YacineNewsBundle/Resources/config/services.yml" }
    - { resource: "@WissemCondidatBundle/Resources/config/services.yml" }



# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    #fos config
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: DataBundle\Entity\User
    from_email:
        address: aaaa
        sender_name: aaaaaaa
nomaya_social:
    buttons:
        facebook:
            url:            "https://web.facebook.com/Thuggies-__CarGo-1461276900599468"
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      true
            layout:         "button_count"
        twitter:
            url:            null
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            "NadaTc"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    theme:                  'default' # optional
knp_paginator:
    page_range:                 5          # default page range used in pagination control
    default_options:
        page_name:              page       # page query parameter name
        sort_field_name:        sort       # sort field query parameter name
        sort_direction_name:    direction  # sort direction query parameter name
        distinct:               true       # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig                         # sort link template
hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    connect:
        confirmation: true
        account_connector: my.custom.user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook:    facebook_id

    resource_owners:
        facebook:
            type:                facebook
            client_id:           1303039546440219
            client_secret:       b998b99fc566424d9b029fef396a48be

            scope:                "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email: email
            options:
                display: page

services:
    my.custom.user_provider:
        class:        MyApp\UserBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]
vich_uploader:
    db_driver: orm
    mappings:
        cours_image:
            uri_prefix:         /images/cours
            upload_destination: '%kernel.root_dir%/../web/images/cours'
            inject_on_load:     true
            delete_on_update:   false
            delete_on_remove:   true
            namer:   vich_uploader.namer_origname
        lesson_image:
            uri_prefix:         /images/lesson
            upload_destination: '%kernel.root_dir%/../web/images/lesson'
            inject_on_load:     true
            delete_on_update:   false
            delete_on_remove:   true
            namer:   vich_uploader.namer_origname
        quiz_image:
            uri_prefix:         /images/quiz
            upload_destination: '%kernel.root_dir%/../web/images/quiz'
            inject_on_load:     true
            delete_on_update:   false
            delete_on_remove:   true
            namer:   vich_uploader.namer_origname
        product_image:
            uri_prefix:         /images/products
            upload_destination: 'C:/wamp/www/image'
        actualite_image:
            uri_prefix:         /images/actualite
            upload_destination: '%kernel.root_dir%/../web/images/actualite'

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        user_image:
            uri_prefix:         /images/user
            upload_destination: '%kernel.root_dir%/../web/images/user'
            inject_on_load:     true
            delete_on_update:   false
            delete_on_remove:   true
            namer:   vich_uploader.namer_origname


