wissem_condidat:
    resource: "@WissemCondidatBundle/Resources/config/routing.yml"
    prefix:   /

yacine_news:
    resource: "@YacineNewsBundle/Resources/config/routing.yml"
    prefix:   /

farah_chat:
    resource: "@FarahChatBundle/Resources/config/routing.yml"
    prefix:   /

graphe:
    resource: "@GrapheBundle/Resources/config/routing.yml"
    prefix:   /

nada_map:
    resource: "@NadaMapBundle/Resources/config/routing.yml"
    prefix:   /


data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /

nada_auto_ecole:
    resource: "@NadaAutoEcoleBundle/Resources/config/routing.yml"
    prefix:   /

my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path:     /login/check-facebook

google_login:
    path:     /login/check-google

custom_login:
    path: /login/check-custom

github_login:
    path: /login/check-github