nada_auto_ecole_homepage:
    path:     /
    defaults: { _controller: NadaAutoEcoleBundle:Default:index }

nada_auto_ecole_AgentAccueil:
    path:     /agentaccueil
    defaults: { _controller: NadaAutoEcoleBundle:Welcome:Agent }
nada_auto_ecole_UserAccueil:
    path:     /useraccueil
    defaults: { _controller: NadaAutoEcoleBundle:Welcome:User }
nada_auto_ecole_Accueil:
    path:     /accueil
    defaults: { _controller: NadaAutoEcoleBundle:Welcome:Accueil }


nada_auto_ecole_Cours:
    path:     /listcours
    defaults: { _controller: NadaAutoEcoleBundle:Cours:AfficheCours }
nada_auto_ecole_SuppCours:
    path:     /suppCours/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Cours:SuppCours }
nada_auto_ecole_CoursAdd:
    path:     /addcours
    defaults: { _controller: NadaAutoEcoleBundle:Cours:AjoutCours }
nada_auto_ecole_CoursEdit:
    path:     /editcours/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Cours:ModifCours }
nada_auto_ecole_ShowLessonCours:
    path:     /showwlessoncours/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Cours:ShowLessonCours }



nada_auto_ecole_Test:
    path:     /listtest
    defaults: { _controller: NadaAutoEcoleBundle:Tests:AfficheTest }
nada_auto_ecole_TestAdd:
    path:     /addtest
    defaults: { _controller: NadaAutoEcoleBundle:Tests:AjoutTests }
nada_auto_ecole_TestEdit:
    path:     /edittest/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Tests:ModifTest }
nada_auto_ecole_SuppTest:
    path:     /suppTest/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Tests:SuppTest }
nada_auto_ecole_ListFrontTest:
    path:     /listfronttest
    defaults: { _controller: NadaAutoEcoleBundle:Tests:AfficheTestFront }


nada_auto_ecole_quiz:
    path:     /showAllQuiz
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:showAllQuiz }
nada_auto_ecole_showQuizTest:
    path:     /showquiz/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:showQuizQ }
nada_auto_ecole_QuizAdd:
    path:     /addquiz
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:AjoutQuiz }
nada_auto_ecole_QuizEdit:
    path:     /editQuiz/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:ModifQuiz }
nada_auto_ecole_showQuizTes2t:
    path:     /showquiz2/{id}/{idt}
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:showQuizQ }
nada_auto_ecole_SuppQuizt:
    path:     /suppQuiz/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:SuppQuiz }
nada_auto_ecole_FrontQuiz:
    path:     /frontQuiz/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:showQuizFrontQ }

nada_auto_ecole_Taxi:
    path:     /taxi
    defaults: { _controller: NadaAutoEcoleBundle:Quiz:Taxi }

nada_auto_ecole_CoursFront:
    path:     /listcoursFront
    defaults: { _controller: NadaAutoEcoleBundle:Cours:AfficheCoursFront }


nada_auto_ecole_LessonFront:
    path:     /listLessonFront/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Cours:AfficheLesson }
nada_auto_ecole_LessonList:
    path:     /listLesson
    defaults: { _controller: NadaAutoEcoleBundle:Lesson:AfficheLesson }
nada_auto_ecole_LessonEdit:
    path:     /editLesson/{id}
    defaults: { _controller: NadaAutoEcoleBundle:Lesson:ModifLesson }
nada_auto_ecole_LessonSupp:
    path:     /suupLesson
    defaults: { _controller: NadaAutoEcoleBundle:Lesson:SuppLesson }
nada_auto_ecole_LessonAdd:
    path:     /addlesson
    defaults: { _controller: NadaAutoEcoleBundle:Lesson:AjoutLesson }






